<a href="https://colab.research.google.com/github/rashidkhan-dev0101/Flower_prediction/blob/main/Iris_ML_Model_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:

import pandas as pd
from sklearn.datasets import load_iris

# Load the built-in Iris dataset
iris = load_iris(as_frame=True)

# Convert the dataset into a DataFrame
df = iris.frame

# Display the first five rows
print(df.head())

# Check the dataset dimensions
print("\nDataset shape:", df.shape)

# Display the column names
print("\nColumns:")
print(df.columns.tolist())

# Count the examples in each class
print("\nTarget distribution:")
print(df["target"].value_counts().sort_index())

# Display the species names
print("\nSpecies:", iris.target_names)




   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  

Dataset shape: (150, 5)

Columns:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'target']

Target distribution:
target
0    50
1    50
2    50
Name: count, dtype: int64

Species: ['setosa' 'versicolor' 'virginica']


In [5]:
# Separate input features (X) and target labels (y)

X = df.drop("target", axis=1)
y = df["target"]

# Display the features
print("Features (X):")
print(X.head())

# Display the target labels
print("\nTarget (y):")
print(y.head())

# Check dimensions
print("\nX shape:", X.shape)
print("y shape:", y.shape)

Features (X):
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

Target (y):
0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

X shape: (150, 4)
y shape: (150,)


In [6]:

from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Check the sizes of each set
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (120, 4)
X_test shape: (30, 4)
y_train shape: (120,)
y_test shape: (30,)


In [7]:

from sklearn.neighbors import KNeighborsClassifier

# 1. Create the model
model = KNeighborsClassifier(n_neighbors=3)

# 2. Train the model using training data
model.fit(X_train, y_train)

print("Model training completed!")

Model training completed!


In [8]:

# Predict the species of flowers in the test dataset
y_pred = model.predict(X_test)

# Display the first 10 predictions
print("Predicted labels:")
print(y_pred[:10])

# Display the actual labels
print("\nActual labels:")
print(y_test.iloc[:10].to_numpy())

# Compare predictions with actual labels
print("\nPrediction correct?")
print(y_pred[:10] == y_test.iloc[:10].to_numpy())

Predicted labels:
[0 2 1 1 0 1 0 0 2 1]

Actual labels:
[0 2 1 1 0 1 0 0 2 1]

Prediction correct?
[ True  True  True  True  True  True  True  True  True  True]


In [9]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", accuracy)
print("Accuracy Percentage:", accuracy * 100, "%")

# Display the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Display the detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Model Accuracy: 1.0
Accuracy Percentage: 100.0 %

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00        10
   virginica       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [11]:


# Create a new flower using the same feature names
new_flower = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2]],
    columns=X.columns
)

# Predict the species
prediction = model.predict(new_flower)

# Convert the numeric label into a species name
species = iris.target_names[prediction[0]]

print("Predicted species:", species)

Predicted species: setosa


In [12]:

# Try three different flower measurements
flowers = pd.DataFrame(
    [
        [5.1, 3.5, 1.4, 0.2],
        [6.0, 2.9, 4.5, 1.5],
        [6.5, 3.0, 5.8, 2.2]
    ],
    columns=X.columns
)

# Predict all three flowers
predictions = model.predict(flowers)

# Display the results
for i, prediction in enumerate(predictions):
    species = iris.target_names[prediction]
    print(f"Flower {i + 1}: {species}")

Flower 1: setosa
Flower 2: versicolor
Flower 3: virginica


In [13]:

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

for k in [1, 3, 5, 7, 9]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    predictions = knn.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)

    print(f"K = {k}: Accuracy = {accuracy * 100:.2f}%")

K = 1: Accuracy = 96.67%
K = 3: Accuracy = 100.00%
K = 5: Accuracy = 100.00%
K = 7: Accuracy = 96.67%
K = 9: Accuracy = 100.00%
